In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("vendas.csv")
df

         data   produto    categoria  valor  quantidade
0  2025-01-01  Notebook  Eletrônicos   3500           1
1  2025-01-02     Mouse  Eletrônicos     80           2
2  2025-01-03   Cadeira       Móveis    500           1
3  2025-02-01   Teclado  Eletrônicos    150           1
4  2025-02-05  Notebook  Eletrônicos   3500           1
5  2025-03-01      Mesa       Móveis    700           1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   data        6 non-null      object
 1   produto     6 non-null      object
 2   categoria   6 non-null      object
 3   valor       6 non-null      int64
 4   quantidade  6 non-null      int64
dtypes: int64(2), object(3)
memory usage: 372.0+ bytes

In [4]:
df['faturamento'] = df['valor'] * df['quantidade']
df

         data   produto    categoria  valor  quantidade  faturamento
0  2025-01-01  Notebook  Eletrônicos   3500           1         3500
1  2025-01-02     Mouse  Eletrônicos     80           2          160
2  2025-01-03   Cadeira       Móveis    500           1          500
3  2025-02-01   Teclado  Eletrônicos    150           1          150
4  2025-02-05  Notebook  Eletrônicos   3500           1         3500
5  2025-03-01      Mesa       Móveis    700           1          700

In [5]:
df['faturamento'].sum()

np.int64(8510)

In [6]:
df.groupby('produto')['quantidade'].sum()

produto
Cadeira     1
Mesa        1
Mouse       2
Notebook    2
Teclado     1
Name: quantidade, dtype: int64

In [8]:
df['data'] = pd.to_datetime(df['data'])

In [9]:
df['mes'] = df['data'].dt.month
df.groupby('mes')['faturamento'].sum()

mes
1    4160
2    3650
3     700
Name: faturamento, dtype: int64

In [10]:
faturamento_total = df['faturamento'].sum()
top_produtos = df.groupby('produto')['quantidade'].sum()
vendas_mes = df.groupby('mes')['faturamento'].sum()

print("Faturamento total:", faturamento_total)
print("\nTop produtos:\n", top_produtos)
print("\nVendas por mês:\n", vendas_mes)

Faturamento total: 8510

Top produtos:
 produto
Cadeira     1
Mesa        1
Mouse       2
Notebook    2
Teclado     1
Name: quantidade, dtype: int64

Vendas por mês:
 mes
1    4160
2    3650
3     700
Name: faturamento, dtype: int64